[functions.notify-new-task]
verify_jwt = false

[functions.meeting-reminders]
verify_jwt = false

[functions.notify-student-task]
verify_jwt = false

[functions.notify-instructor-task]
verify_jwt = false

[functions.instructor-lesson-reminders]
verify_jwt = false
