-- הרץ ב-Supabase SQL Editor לפני שימוש במודול ההנהלה
-- Run in Supabase SQL Editor before using the management module

-- מחלקה למשתמשי הנהלה (אופציונלי לשאר התפקידים)
ALTER TABLE users ADD COLUMN IF NOT EXISTS department text DEFAULT 'general';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url text;

-- ישיבות הנהלה
CREATE TABLE IF NOT EXISTS management_meetings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  meeting_type text NOT NULL DEFAULT 'weekly',
  topic_department text,
  meeting_date timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'scheduled',
  summary text,
  created_by_username text,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- נושאים לסדר היום
CREATE TABLE IF NOT EXISTS meeting_agenda_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id bigint NOT NULL REFERENCES management_meetings(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  item_type text NOT NULL DEFAULT 'discussion',
  submitted_by_username text,
  sort_order int NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- משימות הנהלה
CREATE TABLE IF NOT EXISTS management_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  assignee_username text NOT NULL,
  created_by_username text NOT NULL,
  department text DEFAULT 'general',
  meeting_id bigint REFERENCES management_meetings(id) ON DELETE SET NULL,
  agenda_item_id bigint REFERENCES meeting_agenda_items(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'open',
  priority text NOT NULL DEFAULT 'normal',
  due_date date,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- עדכונים ודיווחי סגירה
CREATE TABLE IF NOT EXISTS management_task_updates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES management_tasks(id) ON DELETE CASCADE,
  author_username text NOT NULL,
  update_type text NOT NULL DEFAULT 'comment',
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mgmt_tasks_assignee ON management_tasks(assignee_username);
CREATE INDEX IF NOT EXISTS idx_mgmt_tasks_created_by ON management_tasks(created_by_username);
CREATE INDEX IF NOT EXISTS idx_mgmt_tasks_status ON management_tasks(status);
CREATE INDEX IF NOT EXISTS idx_meeting_agenda_meeting ON meeting_agenda_items(meeting_id);

-- RLS פתוח לשלב ראשון (התאם לפי מדיניות האבטחה שלכם)
ALTER TABLE management_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_agenda_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE management_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE management_task_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mgmt_meetings_all" ON management_meetings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "mgmt_agenda_all" ON meeting_agenda_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "mgmt_tasks_all" ON management_tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "mgmt_updates_all" ON management_task_updates FOR ALL USING (true) WITH CHECK (true);
