-- הרץ ב-Supabase SQL Editor — מניעת שליחה כפולה
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS notification_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_key text NOT NULL UNIQUE,
  sent_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notification_log_sent_at ON notification_log(sent_at);

ALTER TABLE notification_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notification_log_all" ON notification_log FOR ALL USING (true) WITH CHECK (true);

-- הגדרת cron לתזכורות ישיבות: הרץ בנפרד את meeting_reminders_cron.sql (אחרי deploy)
-- הגדרת cron לתזכורות שיעור מדריך: הרץ בנפרד את instructor_lesson_reminders_cron.sql (אחרי deploy)
