-- הרץ ב-Supabase SQL Editor לפני בדיקת Push
-- Run in Supabase SQL Editor before testing push notifications

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  platform text NOT NULL CHECK (platform IN ('ios', 'android')),
  token text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (username, platform, token)
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_username ON push_subscriptions(username);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_active ON push_subscriptions(active);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "push_subscriptions_all" ON push_subscriptions FOR ALL USING (true) WITH CHECK (true);
