-- Trial leads (שיעור ניסיון) schema + RLS
-- Run as postgres role

CREATE TABLE IF NOT EXISTS public.trial_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  student_full_name TEXT NOT NULL,
  group_id BIGINT NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  trial_date DATE,
  source_channel TEXT NOT NULL DEFAULT 'whatsapp',
  status TEXT NOT NULL DEFAULT 'before_class',
  notes TEXT,
  attended_trial BOOLEAN NOT NULL DEFAULT false,
  attended_marked_at TIMESTAMPTZ,
  attended_marked_by TEXT,
  immediate_sent_at TIMESTAMPTZ,
  followup_sent_at TIMESTAMPTZ,
  last_delivery_status TEXT,
  last_delivery_error TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT trial_leads_status_check
    CHECK (status IN ('before_class', 'after_class', 'thinking', 'not_interested', 'registered')),
  CONSTRAINT trial_leads_source_channel_check
    CHECK (source_channel IN ('whatsapp', 'phone'))
);

CREATE INDEX IF NOT EXISTS idx_trial_leads_group_id ON public.trial_leads(group_id);
CREATE INDEX IF NOT EXISTS idx_trial_leads_parent_phone ON public.trial_leads(parent_phone);
CREATE INDEX IF NOT EXISTS idx_trial_leads_trial_date ON public.trial_leads(trial_date);
CREATE INDEX IF NOT EXISTS idx_trial_leads_status ON public.trial_leads(status);

CREATE TABLE IF NOT EXISTS public.trial_lead_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_lead_id BIGINT NOT NULL REFERENCES public.trial_leads(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  previous_status TEXT,
  next_status TEXT,
  previous_attended_trial BOOLEAN,
  next_attended_trial BOOLEAN,
  changed_by TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  note TEXT
);

CREATE INDEX IF NOT EXISTS idx_trial_history_trial_id ON public.trial_lead_status_history(trial_lead_id);

CREATE OR REPLACE FUNCTION public.touch_trial_leads_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := timezone('utc', now());
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.current_app_user_identity()
RETURNS TABLE(username TEXT, full_name TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.username, u.full_name
  FROM public.users u
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
$$;

ALTER FUNCTION public.current_app_user_identity() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.current_app_user_identity() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_user_identity() TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.can_access_trial_group(target_group_id BIGINT)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  app_username TEXT;
  app_full_name TEXT;
  ok BOOLEAN := false;
BEGIN
  IF public.is_staff_management() THEN
    RETURN true;
  END IF;

  IF NOT public.is_staff_instructor() THEN
    RETURN false;
  END IF;

  SELECT i.username, i.full_name
    INTO app_username, app_full_name
  FROM public.current_app_user_identity() i;

  IF app_username IS NULL AND app_full_name IS NULL THEN
    RETURN false;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.groups g
    WHERE g.id = target_group_id
      AND (
        g.instructor = app_username
        OR g.instructor = app_full_name
        OR g.instructor = CONCAT(app_full_name, ' (זמני)')
        OR g.instructor = CONCAT(app_full_name, ' (זמנית)')
      )
  ) INTO ok;

  RETURN COALESCE(ok, false);
END;
$$;

ALTER FUNCTION public.can_access_trial_group(BIGINT) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.can_access_trial_group(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_access_trial_group(BIGINT) TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.enforce_trial_leads_instructor_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  app_username TEXT;
BEGIN
  IF public.is_staff_management() THEN
    RETURN NEW;
  END IF;

  IF NOT public.is_staff_instructor() THEN
    RAISE EXCEPTION 'Not allowed to update trial lead';
  END IF;

  IF NOT public.can_access_trial_group(OLD.group_id) THEN
    RAISE EXCEPTION 'Instructor cannot update this group trial lead';
  END IF;

  IF NEW.parent_name IS DISTINCT FROM OLD.parent_name
    OR NEW.parent_phone IS DISTINCT FROM OLD.parent_phone
    OR NEW.student_full_name IS DISTINCT FROM OLD.student_full_name
    OR NEW.group_id IS DISTINCT FROM OLD.group_id
    OR NEW.trial_date IS DISTINCT FROM OLD.trial_date
    OR NEW.source_channel IS DISTINCT FROM OLD.source_channel
    OR NEW.status IS DISTINCT FROM OLD.status
    OR NEW.notes IS DISTINCT FROM OLD.notes
    OR NEW.immediate_sent_at IS DISTINCT FROM OLD.immediate_sent_at
    OR NEW.followup_sent_at IS DISTINCT FROM OLD.followup_sent_at
    OR NEW.last_delivery_status IS DISTINCT FROM OLD.last_delivery_status
    OR NEW.last_delivery_error IS DISTINCT FROM OLD.last_delivery_error
    OR NEW.created_by IS DISTINCT FROM OLD.created_by
  THEN
    RAISE EXCEPTION 'Instructors can only update attendance fields';
  END IF;

  SELECT i.username INTO app_username
  FROM public.current_app_user_identity() i;

  IF NEW.attended_trial IS DISTINCT FROM OLD.attended_trial THEN
    NEW.attended_marked_at := timezone('utc', now());
    NEW.attended_marked_by := app_username;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.log_trial_lead_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.trial_lead_status_history (
      trial_lead_id,
      event_type,
      previous_status,
      next_status,
      previous_attended_trial,
      next_attended_trial,
      changed_by,
      note
    ) VALUES (
      NEW.id,
      'created',
      NULL,
      NEW.status,
      NULL,
      NEW.attended_trial,
      NEW.created_by,
      'trial lead created'
    );
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF NEW.status IS DISTINCT FROM OLD.status OR NEW.attended_trial IS DISTINCT FROM OLD.attended_trial THEN
      INSERT INTO public.trial_lead_status_history (
        trial_lead_id,
        event_type,
        previous_status,
        next_status,
        previous_attended_trial,
        next_attended_trial,
        changed_by,
        note
      ) VALUES (
        NEW.id,
        CASE
          WHEN NEW.attended_trial IS DISTINCT FROM OLD.attended_trial THEN 'attendance_marked'
          ELSE 'status_changed'
        END,
        OLD.status,
        NEW.status,
        OLD.attended_trial,
        NEW.attended_trial,
        COALESCE(NEW.updated_by, NEW.attended_marked_by),
        NULL
      );
    END IF;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_trial_leads_touch_updated_at ON public.trial_leads;
CREATE TRIGGER trg_trial_leads_touch_updated_at
BEFORE UPDATE ON public.trial_leads
FOR EACH ROW
EXECUTE FUNCTION public.touch_trial_leads_updated_at();

DROP TRIGGER IF EXISTS trg_trial_leads_instructor_guard ON public.trial_leads;
CREATE TRIGGER trg_trial_leads_instructor_guard
BEFORE UPDATE ON public.trial_leads
FOR EACH ROW
EXECUTE FUNCTION public.enforce_trial_leads_instructor_update();

DROP TRIGGER IF EXISTS trg_trial_leads_history_insert ON public.trial_leads;
CREATE TRIGGER trg_trial_leads_history_insert
AFTER INSERT ON public.trial_leads
FOR EACH ROW
EXECUTE FUNCTION public.log_trial_lead_changes();

DROP TRIGGER IF EXISTS trg_trial_leads_history_update ON public.trial_leads;
CREATE TRIGGER trg_trial_leads_history_update
AFTER UPDATE ON public.trial_leads
FOR EACH ROW
EXECUTE FUNCTION public.log_trial_lead_changes();

ALTER TABLE public.trial_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trial_lead_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trial_leads_admin_all" ON public.trial_leads;
DROP POLICY IF EXISTS "trial_leads_instructor_select" ON public.trial_leads;
DROP POLICY IF EXISTS "trial_leads_instructor_update_attendance" ON public.trial_leads;
DROP POLICY IF EXISTS "trial_history_admin_all" ON public.trial_lead_status_history;
DROP POLICY IF EXISTS "trial_history_instructor_select" ON public.trial_lead_status_history;
DROP POLICY IF EXISTS "trial_history_staff_insert" ON public.trial_lead_status_history;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.trial_leads TO authenticated;
GRANT SELECT, INSERT ON public.trial_lead_status_history TO authenticated;
REVOKE ALL ON public.trial_leads FROM anon;
REVOKE ALL ON public.trial_lead_status_history FROM anon;

CREATE POLICY "trial_leads_admin_all"
ON public.trial_leads
FOR ALL TO authenticated
USING (public.is_staff_management() = true)
WITH CHECK (public.is_staff_management() = true);

CREATE POLICY "trial_leads_instructor_select"
ON public.trial_leads
FOR SELECT TO authenticated
USING (public.can_access_trial_group(group_id) = true);

CREATE POLICY "trial_leads_instructor_update_attendance"
ON public.trial_leads
FOR UPDATE TO authenticated
USING (public.can_access_trial_group(group_id) = true)
WITH CHECK (public.can_access_trial_group(group_id) = true);

CREATE POLICY "trial_history_admin_all"
ON public.trial_lead_status_history
FOR SELECT TO authenticated
USING (public.is_staff_management() = true);

CREATE POLICY "trial_history_instructor_select"
ON public.trial_lead_status_history
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.trial_leads tl
    WHERE tl.id = trial_lead_status_history.trial_lead_id
      AND public.can_access_trial_group(tl.group_id) = true
  )
);

CREATE POLICY "trial_history_staff_insert"
ON public.trial_lead_status_history
FOR INSERT TO authenticated
WITH CHECK (
  public.is_staff_management() = true
  OR public.is_staff_instructor() = true
);

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;