-- =============================================================================
-- פסגת יוניקורן — הרצה חד־פעמית ב-Supabase
-- =============================================================================
-- איך להריץ:
--   1. פתח Supabase → SQL Editor
--   2. ודא ש-Role = postgres (ברירת מחדל)
--   3. הדבק את כל הקובץ הזה → Run
--
-- אחרי ההרצה:
--   כניסה ל-aragon-platform:
--     שם משתמש: יוניקורן
--     סיסמה:    AragonSecurity91!
-- =============================================================================

-- ---------- טבלה ----------
CREATE TABLE IF NOT EXISTS public.unicorn_challenge_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_full_name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  grade TEXT NOT NULL,
  parent_name TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  city TEXT NOT NULL,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  part12_percent INTEGER NOT NULL DEFAULT 0,
  passed BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'failed',
  notes TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT unicorn_challenge_status_check
    CHECK (status IN ('passed', 'failed', 'pending_committee'))
);

CREATE INDEX IF NOT EXISTS idx_unicorn_challenge_created_at
  ON public.unicorn_challenge_submissions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_unicorn_challenge_status
  ON public.unicorn_challenge_submissions (status);
CREATE INDEX IF NOT EXISTS idx_unicorn_challenge_parent_phone
  ON public.unicorn_challenge_submissions (parent_phone);

CREATE OR REPLACE FUNCTION public.touch_unicorn_challenge_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := timezone('utc', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_unicorn_challenge_touch ON public.unicorn_challenge_submissions;
CREATE TRIGGER trg_unicorn_challenge_touch
  BEFORE UPDATE ON public.unicorn_challenge_submissions
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_unicorn_challenge_updated_at();

-- ---------- RPC לאתר (שמירת הגשה) ----------
CREATE OR REPLACE FUNCTION public.create_unicorn_challenge_submission(
  p_student_full_name TEXT,
  p_school_name TEXT,
  p_grade TEXT,
  p_parent_name TEXT,
  p_parent_phone TEXT,
  p_city TEXT,
  p_answers JSONB,
  p_score_breakdown JSONB,
  p_part12_percent INTEGER,
  p_passed BOOLEAN,
  p_status TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_id BIGINT;
  clean_student TEXT := trim(COALESCE(p_student_full_name, ''));
  clean_school TEXT := trim(COALESCE(p_school_name, ''));
  clean_grade TEXT := trim(COALESCE(p_grade, ''));
  clean_parent TEXT := trim(COALESCE(p_parent_name, ''));
  clean_phone TEXT := trim(COALESCE(p_parent_phone, ''));
  clean_city TEXT := trim(COALESCE(p_city, ''));
  clean_status TEXT := trim(COALESCE(p_status, ''));
BEGIN
  IF clean_student = '' OR clean_school = '' OR clean_grade = ''
     OR clean_parent = '' OR clean_phone = '' OR clean_city = '' THEN
    RAISE EXCEPTION 'missing required fields';
  END IF;

  IF clean_status NOT IN ('passed', 'failed', 'pending_committee') THEN
    RAISE EXCEPTION 'invalid status';
  END IF;

  INSERT INTO public.unicorn_challenge_submissions (
    student_full_name,
    school_name,
    grade,
    parent_name,
    parent_phone,
    city,
    answers,
    score_breakdown,
    part12_percent,
    passed,
    status
  ) VALUES (
    clean_student,
    clean_school,
    clean_grade,
    clean_parent,
    clean_phone,
    clean_city,
    COALESCE(p_answers, '{}'::jsonb),
    COALESCE(p_score_breakdown, '{}'::jsonb),
    COALESCE(p_part12_percent, 0),
    COALESCE(p_passed, false),
    clean_status
  )
  RETURNING id INTO new_id;

  RETURN new_id;
END;
$$;

ALTER FUNCTION public.create_unicorn_challenge_submission(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, INTEGER, BOOLEAN, TEXT
) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.create_unicorn_challenge_submission(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, INTEGER, BOOLEAN, TEXT
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_unicorn_challenge_submission(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, INTEGER, BOOLEAN, TEXT
) TO anon, authenticated, service_role;

-- ---------- הרשאות דשבורד (role = unicorn) ----------
CREATE OR REPLACE FUNCTION public.is_unicorn_reviewer()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid;
  ok boolean;
BEGIN
  uid := auth.uid();
  IF uid IS NULL THEN
    RETURN false;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE auth_user_id = uid
      AND role = 'unicorn'
      AND COALESCE(is_active, true) = true
  ) INTO ok;

  RETURN COALESCE(ok, false);
END;
$$;

ALTER FUNCTION public.is_unicorn_reviewer() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.is_unicorn_reviewer() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_unicorn_reviewer() TO anon, authenticated, service_role;

ALTER TABLE public.unicorn_challenge_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "unicorn_challenge_select_reviewer"
  ON public.unicorn_challenge_submissions;
CREATE POLICY "unicorn_challenge_select_reviewer"
  ON public.unicorn_challenge_submissions
  FOR SELECT TO authenticated
  USING (public.is_unicorn_reviewer() = true);

DROP POLICY IF EXISTS "unicorn_challenge_update_reviewer"
  ON public.unicorn_challenge_submissions;
CREATE POLICY "unicorn_challenge_update_reviewer"
  ON public.unicorn_challenge_submissions
  FOR UPDATE TO authenticated
  USING (public.is_unicorn_reviewer() = true)
  WITH CHECK (public.is_unicorn_reviewer() = true);

DROP POLICY IF EXISTS "unicorn_challenge_delete_reviewer"
  ON public.unicorn_challenge_submissions;
CREATE POLICY "unicorn_challenge_delete_reviewer"
  ON public.unicorn_challenge_submissions
  FOR DELETE TO authenticated
  USING (public.is_unicorn_reviewer() = true);

GRANT SELECT, UPDATE, DELETE ON public.unicorn_challenge_submissions TO authenticated;
GRANT ALL ON public.unicorn_challenge_submissions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.unicorn_challenge_submissions_id_seq TO authenticated, service_role;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.unicorn_challenge_submissions;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------- משתמש אפליקציה: יוניקורן ----------
-- אם נוצר קודם unicorn באנגלית — ממירים לעברית
UPDATE public.users
SET
  username = 'יוניקורן',
  password = 'AragonSecurity91!',
  role = 'unicorn',
  full_name = 'ועדת פסגת יוניקורן',
  department = 'unicorn',
  is_active = true
WHERE username IN ('unicorn', 'יוניקורן');

INSERT INTO public.users (username, password, role, full_name, department, is_active, coins, ils_balance)
SELECT 'יוניקורן', 'AragonSecurity91!', 'unicorn', 'ועדת פסגת יוניקורן', 'unicorn', true, 0, 0
WHERE NOT EXISTS (
  SELECT 1 FROM public.users u WHERE u.username = 'יוניקורן'
);

-- ---------- יצירת Auth + קישור אוטומטי ----------
-- אימייל פנימי: unicorn@aragon.auth (כמו לוגיסטיקה → logistics@aragon.auth)
DO $$
DECLARE
  v_user_id uuid;
  v_existing_auth_id uuid;
  v_app_user_id bigint;
BEGIN
  SELECT id INTO v_app_user_id
  FROM public.users
  WHERE username = 'יוניקורן'
  LIMIT 1;

  IF v_app_user_id IS NULL THEN
    RAISE EXCEPTION 'משתמש יוניקורן לא נוצר ב-public.users';
  END IF;

  SELECT id INTO v_existing_auth_id
  FROM auth.users
  WHERE lower(email) = 'unicorn@aragon.auth'
  LIMIT 1;

  IF v_existing_auth_id IS NULL THEN
    v_user_id := gen_random_uuid();

    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      confirmation_token,
      recovery_token,
      email_change_token_new,
      email_change,
      is_super_admin
    ) VALUES (
      '00000000-0000-0000-0000-000000000000',
      v_user_id,
      'authenticated',
      'authenticated',
      'unicorn@aragon.auth',
      crypt('AragonSecurity91!', gen_salt('bf')),
      timezone('utc', now()),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"ועדת פסגת יוניקורן"}'::jsonb,
      timezone('utc', now()),
      timezone('utc', now()),
      '',
      '',
      '',
      '',
      false
    );

    INSERT INTO auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      provider_id,
      last_sign_in_at,
      created_at,
      updated_at
    ) VALUES (
      gen_random_uuid(),
      v_user_id,
      jsonb_build_object(
        'sub', v_user_id::text,
        'email', 'unicorn@aragon.auth',
        'email_verified', true,
        'phone_verified', false
      ),
      'email',
      v_user_id::text,
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    );
  ELSE
    v_user_id := v_existing_auth_id;

    UPDATE auth.users
    SET
      encrypted_password = crypt('AragonSecurity91!', gen_salt('bf')),
      email_confirmed_at = COALESCE(email_confirmed_at, timezone('utc', now())),
      updated_at = timezone('utc', now())
    WHERE id = v_user_id;
  END IF;

  UPDATE public.users
  SET
    auth_user_id = v_user_id,
    password = 'AragonSecurity91!',
    role = 'unicorn',
    full_name = 'ועדת פסגת יוניקורן',
    department = 'unicorn',
    is_active = true
  WHERE username = 'יוניקורן';
END $$;

-- בדיקה מהירה — אמור להראות יוניקורן עם auth_user_id מלא
SELECT username, role, password IS NOT NULL AS has_password, auth_user_id
FROM public.users
WHERE username = 'יוניקורן';
